### ISSUE TITLE
Make Drive feature optional and not required

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#114]
There seems to be some confusion with how to get started with the app. There is definitely some of a learning curve, and many users seem to struggle with setting it up.

The onboarding process needs to be improved, and part of that is making Drive optional. The "JSON file" seems to confuse some people, and making this optional should reduce confusion.

**Comment by alanmcramer** [comment]
Would like to see the settings not use JSON.  I find that I need to edit the file via my windows PC in order for it to work without problem.  If I use my Mac, it doesn't work.  Most IPTV apps available use a simple M3U file and some of these apps use their own specific tags within the M3U for specific features.

http://ss-iptv.com/en/users/18-about-m3u

http://siptv.eu/howto/playlist.html

That last example uses either M3U or a specific TXT file.  I would love to not use Drive, but have a TXT file or M3U hosted on my server where I can point Cumulus TV to upon initial setup and just have it sync from my server periodically.

**Comment by bgiesing** [comment]
Maybe instead of making it optional, you can do a combination to maintain app sync but have the "confusing" JSON.

1. Use Drive App Folders to store the data in a hidden part of Drive so people don't have to wonder about the file
2. Only allow editing from the Android App. This would mean they can't use their desktop **BUT**
3. Only implement this after Google releases the Play Store for Chrome so users could install Cumulus on their desktop to edit **OR**
4. Make a small web app that accesses the Drive folder with the API (if possible), loads up the file, and presents a easy editing interface similar to the app.

https://developers.google.com/drive/android/appfolder

**Comment by Fleker** [comment]
AppFolders won't work in Chrome, only on Android, making the point of a
syncable json file moot.

Maybe if Android apps come to Chrome it'd be different.

**Comment by bgiesing** [comment]
@Fleker That's why my comment said:

> 2. Only allow editing from the Android App. This would mean they can't use their desktop BUT
> 3. Only implement this after Google releases the Play Store for Chrome so users could install Cumulus on their desktop to edit

**Comment by bgiesing** [comment]
@Fleker That's why my comment said:

> 2. Only allow editing from the Android App. This would mean they can't use their desktop BUT
> 3. Only implement this after Google releases the Play Store for Chrome so users could install Cumulus on their desktop to edit

Also the syncable file is useful for other things like syncing :smile:. Honestly, I would be fine not able to edit the JSON on the computer as the point of the file as I see it is to sync your sources either across multiple TVs and/or between phone and TV if you manage them on your phone.

**Comment by bgiesing** [comment]
@Fleker Since you mentioned JSON files may be confusing, have you thought about other file types that might be simpler with similar functionality?

[YAML](http://yaml.org/) is a good choice I think plus there's tons of YAML to JSON converter libraries/apps if you wanted to keep it internally as JSON but let users edit in YAML.

**Comment by bgiesing** [comment]
@Fleker I just found this http://hjson.org Could this be a good way to make the JSON less confusing?

**Comment by Fleker** [comment]
Perhaps, although my goal is to make that a power user feature and not be
something the average person needs to use.
