### ISSUE TITLE
New graphics again

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#18]
Now that I have reinstalled Photoshop, I'd like to get a little more creative with the appicon and other graphics. I like the purple & white, but a more creative logo would be neat.

**Comment by Fleker** [comment]
Someone wanted to mock up some new graphics, though I haven't heard back from them yet. I'll leave this here.

**Comment by bgiesing** [comment]
![cumulus tv app icon](https://cloud.githubusercontent.com/assets/7895463/9290028/39039b9c-4348-11e5-882d-fef1f7ed814e.png)

This look good? @Fleker

**Comment by Fleker** [comment]
Yeah I like that. Any graphics will have to match the required dimensions.

**Comment by bgiesing** [comment]
I have the ai file, so you can scale it without losing quality and change any aspect!

https://drive.google.com/file/d/0B3DhUCRnvErzYW9fYmZPYURKZGM/view?usp=sharing

**Comment by Fleker** [comment]
Great!

The app icon is 512x512
The TV banner is 320x180
The store banner is 1024x500

**Comment by bgiesing** [comment]
@Fleker Here they are!

---

## App Icon
![cumulus-tv_app-icon](https://cloud.githubusercontent.com/assets/7895463/9290246/cc4c823a-4350-11e5-878e-fd028e78d3f9.png)
## Store Banner
![cumulus-tv_store-banner](https://cloud.githubusercontent.com/assets/7895463/9290248/cc5eedb2-4350-11e5-94a3-d511ea246f50.png)
## TV Banner
![cumulus-tv_tv-banner](https://cloud.githubusercontent.com/assets/7895463/9290247/cc5cf11a-4350-11e5-93e7-c7b3dd0b3125.png)

**Comment by bgiesing** [comment]
@Fleker And the updated AI: https://drive.google.com/file/d/0B3DhUCRnvErzYW9fYmZPYURKZGM/view?usp=sharing

**Comment by Fleker** [comment]
Awesome! I'll integrate these tonight.

**Comment by Fleker** [comment]
Changed the graphics and added an attribution in the `More` menu for `bgiesing`. Should I refer to you by a different name?

**Comment by bgiesing** [comment]
Nope that's good!

On Sun, Aug 16, 2015, 12:46 AM Nick <notifications@github.com> wrote:

> Changed the graphics and added an attribution in the More menu for
> bgiesing. Should I refer to you by a different name?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Fleker/CumulusTV/issues/18#issuecomment-131492313>.
>



To unsubscribe click: <http://email.giesing.cf/u/eJwljstOwzAQAL8muVGtN14_Dj70ARcQ7SUS9ILW9sYJbRSoWqTw9VRhDnMcTQ7GcMJ6CNv1822yp9bs7f5pfvWPD99v25-2wg1tmqmvmt0JxxczHg_vpfy2xw_8nA-uVBpGHs6rsjhNY90HYRANWaukCDJwo0V7VF2ixnVK2_oSLvJ1nu9tAOusZ4tGEaMgZnCRHPuYXGIkdDlTx-IRfCQdPaYO_lFKiRVKySMr45MAiSX29r605FdluPa3uExdQ4XrP6WGRVU>

**Comment by bgiesing** [comment]
@Fleker Looks like you forgot to update it on the Source loading and stream start screens inside the Live Channels app.

**Comment by Fleker** [comment]
Thanks for the heads up.

**Comment by bgiesing** [comment]
@Fleksy Do you need a transparent version or any background color changes in the logo? Some people were telling me that there's too much white space.

**Comment by Fleker** [comment]
I can make a transparent version.

**Comment by bgiesing** [comment]
@Fleksy however, I have the original source files so it would be higher quality if I did it

**Comment by Fleker** [comment]
Sure. If you can generate transparent versions of the logo I'll put them into the next release.

**Comment by bgiesing** [comment]
@Fleker That's the good part, it's transparent by default! All I had to do was change how it's exported!

![cumulus tv_app icon](https://cloud.githubusercontent.com/assets/7895463/9560753/38e66456-4dec-11e5-807b-cdd13e15ab20.png)

------

PS. You might want to keep the white background version for the Play Store icon.

**Comment by bgiesing** [comment]
@Fleker I tried a variant and I need feedback.

![md-icon](https://cloud.githubusercontent.com/assets/7895463/9560788/0e3ac2d6-4dee-11e5-91e6-8b1dc0a5ed2a.png)

**Comment by Fleker** [comment]
I do like the second version. It'll provide good contrast as a small icon.

**Comment by bgiesing** [comment]
That one would be more for a launcher icon even though Android TV doesn't
use them.

On Sat, Aug 29, 2015, 11:29 AM Nick <notifications@github.com> wrote:

> I do like the second version. It'll provide good contrast as a small icon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Fleker/CumulusTV/issues/18#issuecomment-136007501>.
>



To unsubscribe click: <http://email.giesing.cf/u/eJwljrluAkEQRL9mNzOanqungwkWzCFzSASWwVnPBcuhxQgC_72XdQWlKqn0VMlby1HWrZ80y2eH592HMZvbar0l3n9OF1N7XptKjlV3mr-Nd4vZqi8_X5tmH74r9b48TbaVFlduL6PD4LG71kcfZAooUWcTbLDZAZUIDkThYpMusb77e75dfnuYEOiQGA28RsJwAlMcOsVOWEiKdJ-0dBSzYBSKZCziXwBQiErOJBnsa2AyGibsLw340aF9HJ9hOPXwlWz-AImgRL8>

**Comment by Fleker** [comment]
Maybe that should replace the launcher banner as well.

**Comment by bgiesing** [comment]
Not really the correct styling for that...

On Sat, Aug 29, 2015, 11:49 AM Nick <notifications@github.com> wrote:

> Maybe that should replace the launcher banner as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Fleker/CumulusTV/issues/18#issuecomment-136008909>.
>



To unsubscribe click: <http://email.giesing.cf/u/eJwlTsFugzAU-xo4Vi8JyeMdcqDlMGmHqbtst-nxkrRoZbQUyravX8Qs2ZYs2XLwzrHosveH5nkZ8fNtfXr9WofDQy-_7x-PsWlf2N2_C9MeZ7hnazJhvLUTXbtjfwtrUcHA_WV32lTGoTx7MhgtUOycJk4umsAh1dZ1YDSqxOXkp3i9_BR6D4A1EqMEEpdQo1TCnYpg61ocgyJtVAUpj9lESkhLgn8opRJxRTlj5UhyJ6Jlwnxpm9-d-vm8dNup2Re6-QOLvEeO>

**Comment by Fleker** [comment]
Yes, but a similar design to that with correct dimensions and no drop shadow would make a nice banner.

In the meantime, I'll take the design as is and replace the current small icons in the app.

**Comment by Fleker** [comment]
Added for the latest commit, 1.3.0

**Comment by alanmcramer** [comment]
New icon design is really great however I thought the app was called Cumulus TV. The new icon has CUMULULUS TV with an extra UL in it.

**Comment by Fleker** [comment]
Hmm. You're right.

**Comment by Fleker** [comment]
@bgiesing would you mind correcting this?

**Comment by bgiesing** [comment]
Hey @Fleker, I know you have new graphics now but I just wanted to post another variation I made.

![cumulus tv app icon-v2](https://cloud.githubusercontent.com/assets/7895463/9831107/3b6d48ce-590f-11e5-89da-6f8eb33b4f49.png)

**Comment by Fleker** [comment]
That's interesting, but I'm not sure it vibes with the rest of Android TV.

**Comment by bgiesing** [comment]
@Fleker I was mostly messing around with it but the idea was it to look like a TV with the grey background and the word being "lit up" by the shadow.

**Comment by Fleker** [comment]
The notches along the border don't match the aesthetic very well.

**Comment by bgiesing** [comment]
I know I was experimenting with that part a lot.

**Comment by Fleker** [comment]
It's a nice banner aside from that border.

**Comment by bgiesing** [comment]
@Fleker Without the border

![cumulus tv app icon-v2](https://cloud.githubusercontent.com/assets/7895463/9832108/ef42a10c-5935-11e5-9b48-845d4b6d5708.png)

**Comment by Fleker** [comment]
Yeah that looks nice.

**Comment by bgiesing** [comment]
@Fleker And here's it in the banner size with no corners as that wouldn't fit with other banners

![cumulus tv tv banner-v2](https://cloud.githubusercontent.com/assets/7895463/9832166/7dcac930-5937-11e5-81e0-f9baa16aa8cb.png)

**Comment by Fleker** [comment]
Very nice. Can you also make an icon for the mobile variant?

**Comment by bgiesing** [comment]
@Fleker 512x512

![cumulus tv icon-v2](https://cloud.githubusercontent.com/assets/7895463/9832277/869c9ce2-593b-11e5-9a31-7ef5b0698079.png)

**Comment by Fleker** [comment]
Cool. I'll integrate this in 1.3.5

**Comment by alanmcramer** [comment]
I actually don't like it. I like the current graphics which are very
modern. No offense but this icon set and going seem like a huge step
backward. I'd like to just retain the purple current one.

**Comment by bgiesing** [comment]
@alanmcramer The current ones are so ugly it's stupid! It also is poorly made (shadows not lined up) and is too generic.

**Comment by alanmcramer** [comment]
Wow...What are you like... 10 years old?

I gave an opinion but seems like you got offended in the same way a kid
does. Reading your blog, you seem to comment a lot of the design language
of companies such as Google. I suppose their recent rebrand is also stupid
and ugly to borrow your words from earlier.

Here is some constructive criticism for you around your logo design. The
conjointed C in the logo is not clever. I don't see what it is suppose to
represent. I don't have a dip in the top of my TV set. And there is nothing
placed in that dip (ie. Small flekertech logo) . The choice of font is a
poor one and the use of color palette to split the lettering is not great
either. (Don't know of many, if any great companies using this technique at
all).

I don't think fleker should be changing the logo every release and instead
should be focusing on the application instead of what icon he is going to
use this week.

Lucky this isn't my project. I wouldn't be using anyone who is acting
childish towards views by the general public.... You could have taken this
as a feedback session to get someone else's views on how to improve
sometime rather than shoot them down.  If you read felker's other comments,
he remains professional about his response and explains why something isn't
going to work or at least tries what others suggest. Remember....
Professionals act as they must and not as they feel.

**Comment by Fleker** [comment]
Nop it. Let's not have this degrade into arguments. I'm not the best designer, which is why I've been lenient with switching out logos. However Alan has a point that it keeps switching and so messes with the brand. 

If people don't like this new logo as much as the current design, then I probably shouldn't change it.

Let's keep the discussion civil and work together to create great iconography and branding.

**Comment by bgiesing** [comment]
@alanmcramer Sorry, I was in severe pain when I wrote that due to a injury and wasn't thinking what I was writing as I was on medicine. However, my points were valid about it being generic and not lined up properly. A drop shadow is not supposed to start underneath the logo, it's supposed to be behind it like mine as it casts... well a shadow.

I will admit, my logo isn't the best; but compared to the other logo... That one is just too generic that nobody would remember it. Also, you said mine doesn't represent a TV set; well the current logo does even less. It's just text with a shadow. The logo has to be your first impression. I know many people that would look at that one and think that it's a crummy app when it isn't.

So, even if you don't use my logo... The current one still needs tweaking to improve the aesthetic of it and make it less generic. I would suggest to:

1. Fix the shadow
2. Maybe add some "antennas" since they symbolize TV for lots of people.
3. Maybe add a shape around it like a old-fashioned TV from the 1950s/60s.

**Comment by alanmcramer** [comment]
![ctv_banner](https://cloud.githubusercontent.com/assets/3284938/10861498/3b56a220-7fd1-11e5-850d-94bef97f494a.png)
![cumulus_appicon](https://cloud.githubusercontent.com/assets/3284938/10861500/51b68c06-7fd1-11e5-97d6-ed5ebf785460.png)
Thought I would give it a go.  Cloud is used as Cumulus is a type of cloud and this is cloud TV.  Icon and Banner.  Using same font as current banner.
@Fleker if you want better quality version of the icon, let me know.

**Comment by Fleker** [comment]
Hmm, I still kind of like the current icons.

**Comment by bgiesing** [comment]
@alanmcramer That's amazing.
