### ISSUE TITLE
Sort out channels from URL?

### ISSUE THREAD

**Issue by joq3** [Fleker/CumulusTV#221]
Hi,

I have a m3u8 URL which contains 5000+ channels. Right now I am using Perfect Player, but I would like the integration with Live Channels.
Perfect Player sorts channels in groups (for each country).
Is it possible to do the same way here? I know I can edit the file before reading it. But I will loose the automatically updated file from the URL and have to do this from time to time?

Thank you!

**Comment by Fleker** [comment]
An update I'm currently working on will let you link a URL and
automatically download it every time so that you don't need to import once.

5000 channels is a lot, and I'm interested in how well the app will perform
with that many items.

How does that other app determine which group it should be in? There is
already some grouping based on the channel genres.

On Jan 2, 2017 6:30 AM, "joq3" <notifications@github.com> wrote:

Hi,

I have a m3u8 URL which contains 5000+ channels. Right now I am using
Perfect Player, but I would like the integration with Live Channels.
Perfect Player sorts channels in groups (for each country).
Is it possible to do the same way here? I know I can edit the file before
reading it. But I will loose the automatically updated file from the URL
and have to do this from time to time?

Thank you!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Fleker/CumulusTV/issues/221>, or mute the thread

**Comment by joq3** [comment]
@Fleker Oh, I thought it already did update and pull channels from an URL. Do you have to manually download the m3u8 file and import it now?

I have not tried with the full file (5000), but only 130 channels (edited it first).

Perfect player sorts the channels in groups based on a name of a "channel" that is in the beginning of the country's channels, it is named like this (and isn't a real channel): ######## Sweden ########

**Comment by Fleker** [comment]
Right now it downloads the URL once and doesn't pull it again. It will soon
continue to monitor that URL.

I will try to incorporate that new style into the parser. Is that followed
by actual channels?

**Comment by joq3** [comment]
@Fleker Great, do you have any idea when this will be available? I need the function of monitoring URL.

Yes, it is followed by actual channels.

**Comment by Fleker** [comment]
It should be ready once I fix two small issues.
