### ISSUE TITLE
"Link to an M3u Playlist" Broken in 1.7.3

### ISSUE THREAD

**Issue by cumulususer** [Fleker/CumulusTV#247]
As soon as I add my URL the page displays "Unfortunatley, Cumulus TV has stopped"

Can add more details if needed

**Comment by Fleker** [comment]
Okay. It's probably a parser issue. The crash report should provide enough
information to offer a fix.

On Jan 29, 2017 11:03 AM, "cumulususer" <notifications@github.com> wrote:

As soon as I add my URL the page displays "Unfortunatley, Cumulus TV has
stopped"

Can add more details if needed

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Fleker/CumulusTV/issues/247>, or mute the thread
