### ISSUE TITLE
Ability to add YouTube streams

### ISSUE THREAD

**Issue by alanmcramer** [Fleker/CumulusTV#74]
One of the IPTV channels I want to add is broadcast via a YouTube Live stream.  Would love to have it added as a Live Channel if it is supported somehow.

https://youtu.be/ozn4PYST6oA

**Comment by Fleker** [comment]
I don't believe there is a way to get the stream URL of a YouTube video, just a web URL. I am considering how to use a website as a live stream as a separate project though.

**Comment by bgiesing** [comment]
@Fleker You may be able to do something similar to PlutoTV which embeds the YT video into their player which gets fed into the Live Channel UI.

**Comment by Fleker** [comment]
I know exactly how I would go about implementing it in the software -- just using a webview overlay on a blank HLS stream should work -- but I think it makes more sense for it to be a separate project and keep Cumulus TV just for HLS streams.

**Comment by alanmcramer** [comment]
Unsure why would would want to put Youtube videos in a separate project as such.  There is already an app for that....it's called YouTube.  But I am more talking about those IPTV channels that happen to use YouTube for it's broadcast of live content.  To be able to have all the IPTV channels I use in the one place makes it easier for me as a user, especially once XML TV parsing is complete, then I can load up all the channels in one place and use the TV guide etc.

**Comment by Fleker** [comment]
I would use a separate project which would allow any website to be accessible as a live channel, which would work for a lot of interesting types of projects.

However, that is in the opposite direction of this project. I just published an update which allows you to open m3u8 playlist and automatically import them. You can open an m3u8 file right from a link and add it as a channel.

This HTML-TV project would have much less overhead, just a WebView. The benefit of Live Channels is that it would be a way to curate all these IPTV sources and streams together. Yet HTML-TV project won't be a stream.

Instead of just being just a YouTube video, users could create playlists of videos, basically creating custom live channels that can be shared with others. These custom channels could then be easily played in a browser/WebView. 

Yet HTML-TV would be much more than YouTube, basically extending to any website and any sort of macros due to the way that will be programmed. There could be some room for overlap, but not enough where it would make sense for the end user. It would also be complicated to develop side cases almost everywhere.

**Comment by Fleker** [comment]
After more thought, I believe it would be better to have this "HTML-TV" project as part of Cumulus TV. There's too much redundancy. I'll begin the integration of a WebView into the system soon.

**Comment by alanmcramer** [comment]
Hurrah!

Looking forward to this feature being added.

**Comment by Fleker** [comment]
Being able to use websites as live channels will be available in 1.4.7/1.5

**Comment by Fleker** [comment]
This is now available as a beta.

**Comment by alanmcramer** [comment]
So this forces the YouTube app to open.  Is there anyway this can play the stream directly in the Live Channels app or is that something that isn't supported by the Live Channels app directly?

**Comment by Fleker** [comment]
Yes it does work. You probably shouldn't link to the YouTube video
directly, but the embedded URL that will take the full screen. It may
require a proxy website to get some of the iframe code configured.
